name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: _site
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: jekyll-deploy
    #   # You may pin to the exact commit or the version.
    #   # uses: DavidS/jekyll-deploy@4e59472205269cce9739ac284303e74701fd7e9d
    #   uses: DavidS/jekyll-deploy@1.1.1
    #   with:
    #     # Set to "true" to only build, but not deploy. This is useful for PR testing
    #     build-only: false
    #   env:
    #     JEKYLL_ENV: production
    #     GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
